name: Unit tests

on: [push]

jobs:
  full_test_run:

    env:
      USE_BROWSER_STACK: true

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
      uses: browserstack/github-actions/setup-env@master
      with:
        username: ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    - name: 'BrowserStack Local Tunnel Setup'  # Invokes the setup-local action
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: start
        local-identifier: random

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - name: Cache npm packages
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: NPM install
      run: npm ci

    # - name: Lint TypeScript sources
    #   run: npm run lint

    - name: Bootstrap packages
      run: npm run bootstrap

    - name: Build packages
      run: npm run build

    - name: Unit tests
      run: npm run test:ci

    - name: 'BrowserStackLocal Stop'  # Terminating the BrowserStackLocal tunnel connection
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: stop